'use strict';
const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('fs');
const path = require('path');
const os = require('os');
const crypto = require('crypto');
const { integrationCheck } = require('../../plugins/iris-cure-form-dev/scripts/cure-form-integration-check');
const { runnerFingerprint } = require('../../plugins/iris-cure-form-dev/scripts/cure-form-runner-fingerprint');
const { sha256 } = require('../../plugins/iris-cure-form-dev/scripts/cure-form');
test('integration binds ownership, baseline, fields and current runner evidence', (t) => {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), 'cure-integration-'));
  t.after(() => fs.rmSync(root, { recursive: true, force: true }));
  const save = (name, value) => { const file = path.join(root, name); fs.writeFileSync(file, JSON.stringify(value)); return file; };
  const html = '<div><input id="duplicate" name="x" type="radio"><input id="duplicate" name="x" type="radio"></div>';
  const snapshot = { mapCode: 'Example', templates: [{ rowId: '1', content: html }] };
  const changes = { mapCode: 'Example', templates: [{ rowId: '1', content: html }] };
  const proof = { status: 'passed', snapshotHash: sha256(snapshot), changesHash: sha256(changes), runner: { implementationHash: runnerFingerprint() } };
  const artifact = save('owned.json', {});
  const delivery = { mapCode: 'Example', unresolved: [], files: [{ path: artifact, sha256: crypto.createHash('sha256').update(fs.readFileSync(artifact)).digest('hex') }], snapshot: save('snapshot.json', snapshot), snapshotHash: sha256(snapshot), changes: save('changes.json', changes), previewVerification: save('proof.json', proof) };
  assert.equal(integrationCheck([delivery]).status, 'passed');
  assert.throws(() => integrationCheck([delivery, delivery]), /Duplicate Map/);
  assert.throws(() => integrationCheck([delivery, { ...delivery, mapCode: 'Second' }]), /Overlapping/);
  fs.writeFileSync(artifact, 'changed');
  assert.throws(() => integrationCheck([delivery]), /artifact changed/);
  fs.writeFileSync(artifact, '{}');
  proof.runner.implementationHash = 'old'; save('proof.json', proof);
  assert.throws(() => integrationCheck([delivery]), /Stale/);
  proof.runner.implementationHash = runnerFingerprint();
  changes.templates[0].content = html.replace('name="x"', 'name="changed"');
  proof.changesHash = sha256(changes); save('proof.json', proof); save('changes.json', changes);
  assert.throws(() => integrationCheck([delivery]), /Runtime contract/);
});
